server:
  port: 9999
  servlet:
    context-path: /

# actuator相关配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      enabled: true
      show-details: always

spring:
  application:
    name: IM-SERVER
  thymeleaf:
    # 开发时关闭缓存,不然没法看到实时页面
    cache: false
    # 用非严格的 HTML
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/netty_im?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 4
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 60000
    lettuce: #由于Spring Boot2.x 的改动，连接池相关配置需要通过spring.redis.lettuce.pool或者 spring.redis.jedis.pool 进行配置
      pool:
        max-active: 20 #连接池最大连接数(使用负值表示没有限制) 默认8
        max-wait: -1 #连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 0 #连接池中的最小空闲连接
        max-idle: 10 #连接池中的最大空闲连接
  cloud:
    # consul配置
    consul:
      enabled: false
      host: 192.168.3.168
      port: 8501
      discovery:
        instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
        serviceName: ${spring.application.name}
        prefer-ip-address: true
        register-health-check: true
        # 只能使用health-check-url可以解决consul Service Checks failed的问题
        #        health-check-path: /actuator/health
        health-check-url: http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
        health-check-critical-timeout: 30s
        tags: 聊天服务
